docnoc:
    default:
        cpu:
            min: 10
            max: 180
        memory:
            max: 90
        status:
            - stopped
            - started
        exclude:
            - web
    containers:
        web:
            cpu: 
                min: 30
                max: 200
