docnoc:
    default:
        cpu:
            min: 10
            max: 180
        memory:
            max: 90
        block_write:
            max: 6
        action: restart
    containers:
        web:
            cpu: 
                min: 30
                max: 200
    slack_webhook: https://hooks.slack.com/services/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
